services:
  server:
    build:
      context: ../../
      dockerfile: docker/cs/Dockerfile.server
    environment:
      MODEL_PATH: /app/model/model.h5
      VOCAB_PATH: /app/model/vocab.json
    volumes:
      - ../../model:/app/model
    ports:
      - 5001:5000

  client:
    build:
      context: ../../
      dockerfile: docker/cs/Dockerfile.client
    environment:
      API_BASE_URL: http://server:5000
    ports:
      - 5000:5000