services:
  server:
    build:
      context: ../../
      dockerfile: docker/cs/Dockerfile.server

  client:
    build:
      context: ../../
      dockerfile: docker/cs/Dockerfile.client
    ports:
      - 5000:5000