services:
  ppml_testing:
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile
    volumes:
      - ../../dataset/train:/app/dataset/train:ro
      - ../../dataset/test:/app/dataset/test:ro
      - ../../model/:/app/model/

    # Uncomment the line you want to test

    # Predict
    command: ["python3", "/app/privacypreservingml/cli.py", "predict", "--model", "/app/model/model.h5", "--vocab", "/app/model/vocab.json", "--text-file", "/app/dataset/test/spam/spam_12.txt"]
    
    # Privacy Predict
    # command: ["python3", "/app/privacypreservingml/cli.py", "privacy-predict", "--model", "/app/model/model.h5", "--vocab", "/app/model/vocab.json", "--text-file", "/app/dataset/test/spam/spam_12.txt"]
    
    # Benchmark Predict
    # command: ["python3", "/app/privacypreservingml/cli.py", "benchmark-predict", "--model", "/app/model/model.h5", "--vocab", "/app/model/vocab.json", "--test-dataset", "/app/dataset/test"]

    # CKKS Example
    # command: ["python3", "/app/privacypreservingml/testing/ckks_example.py"]